// Generated by Wrangler by running `wrangler types`

interface Env {
	OTP_STORE: KVNamespace;
	APP_NAME: "ActionQ";
	APP_VERSION: "1.0.0";
	APP_SECRET: string;
	ADMIN_INIT_EMAIL: string;
	ADMIN_INIT_PASSWORD: string;
	DB: D1Database;
}
